config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :movies do
    member do
      post :favorite
      post :unfavorite
    end
    resources :reviews
  end

  namespace :account do
    resources :movies
    resources :reviews
  end
  root 'movies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :reviews

  validates :title, presence: true
  has_many :movie_relationships
  has_many :members, through: :movie_relationships, source: :user
end

app/models/movie_relationship.rb
class MovieRelationship < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  validates :content, presence: true

  scope :recent, -> { order("created_at DESC") }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :movies
  has_many :reviews
  has_many :movie_relationships
  has_many :favorited_movies, :through => :movie_relationships, :source => :movie

  def has_collected?(movie)
    favorited_movies.include?(movie)
  end

  def favorite!(movie)
    favorited_movies << movie
  end

  def unfavorite!(movie)
    favorited_movies.delete(movie)
  end
  
end

app/controllers/account/movies_controller.rb
class Account::MoviesController < ApplicationController
  before_action :authenticate_user!

  def index
    @movies = current_user.favorited_movies
  end
end

app/controllers/account/reviews_controller.rb
class Account::ReviewsController < ApplicationController
  before_action :authenticate_user!

  def index
    @reviews = current_user.reviews
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user! , only: [:new, :create, :edit, :update, :destroy]
  before_action :find_group_and_check_permission, only: [:edit, :update, :destroy]

  def index
    @movies = Movie.all.order("created_at DESC").paginate( :page => params[:page], :per_page => 20)
  end

  def show
    @movie = Movie.find(params[:id])
    @reviews = @movie.reviews.recent.paginate(:page => params[:page], :per_page => 5)
  end

  def new
    @movie = Movie.new
  end

  def edit

  end

  def create
    @movie = Movie.new(movie_params)
    @movie.user = current_user

    if @movie.save
      current_user.favorite!(@movie)
      redirect_to movies_path, notice: "Movie create successfully!"
    else
      render :new
    end
  end

  def update

    if @movie.update(movie_params)
      redirect_to movies_path, notice: "Movie update successfully!"
    else
      render :edit
    end
  end

  def destroy

    @movie.destroy
    redirect_to movies_path, alert: "Movie delete"
  end

  def favorite
    @movie = Movie.find(params[:id])
    if !current_user.has_collected?(@movie)
      current_user.favorite!(@movie)
      flash[:notice] = "收藏成功！"
    else
      flash[:warning] = "你已经收藏了这部电影！"
    end
    redirect_to movie_path(@movie)
  end

  def unfavorite
    @movie = Movie.find(params[:id])
    if current_user.has_collected?(@movie)
      current_user.unfavorite!(@movie)
      flash[:alert] = "已取消收藏"
    else
      flash[:warning] = "你没有收藏怎么取消，XD!"
    end
    redirect_to movie_path(@movie)
  end



  private

  def find_group_and_check_permission
    @movie = Movie.find(params[:id])
    if current_user != @movie.user
      redirect_to root_path, alert: "You have no permisson."
    end
  end

  def movie_params
    params.require(:movie).permit(:title, :description)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def new
    @movie = Movie.find(params[:movie_id])
    if !current_user.has_collected?(@movie)
      redirect_to movie_path(@movie)
      flash[:warning] = "You need to favorite this movie before writing a review."
    end
    @review = Review.new
  end

  def edit
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:id])
  end

  def create
    @movie = Movie.find(params[:movie_id])
    @review = Review.new(review_params)
    @review.movie = @movie
    @review.user = current_user

    if @review.save
      redirect_to movie_path(@movie)
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to account_reviews_path, notice: "Update successfully"
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to account_reviews_path, alert: "Review deleted"
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:warning] = "这是 warning 讯息 ！"
  end

end

app/helpers/account/movies_helper.rb
module Account::MoviesHelper
end

app/helpers/account/reviews_helper.rb
module Account::ReviewsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning" }.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def render_movie_description(movie)
    simple_format(movie.description)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def render_review_content(review)
    simple_format(review.content)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<div class="container-fluid">
  <% if flash.any? %>
    <% user_facing_flashes.each do |key, value| %>
      <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
        <button class="close" data-dismiss="alert">x</button>
        <%= value %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">Copyright ©2017 iMovie
    <br>Design by
    <a href="/">陈威严</a>
  </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!--Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">iMovie</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

        <% if !current_user %>
          <li><%= link_to("注册", new_user_registration_path )%></li>
          <li><%= link_to("登录", new_user_session_path) %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hi!, <%= current_user.email %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to("My Movies", account_movies_path) %></li>
              <li><%= link_to("My Reviews", account_reviews_path) %></li>
              <li class="divider"></li>
              <li><%= link_to("退出", destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li>
        <% end %>

      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Imovie</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
      <%= yield %>

    </div>
    <%= render "common/footer" %>
  </body>

</html>

app/views/movies/_form.html.erb
<%= simple_form_for @movie do |f| %>
  <div class="form-movie">
    <%= f.input :title, input_html: { class: "form-control" } %>
    <%= f.input :description, input_html: { class: "form-control "} %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>
<% end %>

app/views/movies/_movie_item.html.erb
<tr>
  <td>#</td>
  <td><%= link_to(movie.title, movie_path(movie)) %></td>
  <td><%= render_movie_description(movie) %></td>
  <td><%= movie.user.email %></td>
  <td>
    <% if current_user && current_user == movie.user %>
      <%= link_to("Edit", edit_movie_path(movie), class: "btn btn-sm btn-default ") %>
      <%= link_to("Delete", movie_path(movie), class: "btn btn-sm btn-default",
                   method: :delete, data: { confirm: "Are you sure?" } ) %>
    <% end %>
  </td>
</tr>

app/views/movies/_review_item.html.erb
<tr>
  <td><%= render_review_content(review) %></td>
  <td><%= review.user.email %></td>
  <td><%= review.created_at %></td>
<tr>

app/views/movies/edit.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h2>编辑电影</h2>

    <hr>
    <%= render "form" %>

  </div>
</div>

app/views/movies/index.html.erb
<div class="col-md-12">
  <div class="movie">
    <%=  link_to("Add a Movie", new_movie_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Title</th>
        <th>Description</th>
        <th>Creator</th>
      </tr>
    </thead>
    <tbody>
      <%= render :partial => "movie_item", :collection => @movies, :as => :movie %>

    </tbody>
  </table>
  <div class="text-center">
    <%= will_paginate @movies %>
  </div>
</div>

app/views/movies/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h2>新增电影</h2>

    <hr>
    <%= render "form" %>

  </div>
</div>

app/views/movies/show.html.erb
<div class="col-md-12">
  <div class="movie">

    <% if current_user %>
    <span class="pull-right">
      <% if current_user && current_user.has_collected?(@movie) %>
        <label class="label label-success"> 已经收藏 </label>
        <%= link_to("Unfavorite", unfavorite_movie_path(@movie), method: :post, class: "btn btn-default") %>
      <% else %>
        <label class="label label-warning"> 未收藏 </label>
        <%= link_to("Favorite", favorite_movie_path(@movie), method: :post, class: "btn btn-default") %>
      <% end %>
    </span>

    <%= link_to("Write a Review", new_movie_review_path(@movie), class: "btn btn-default pull-right") %>
    <% end %>


    <% if current_user && current_user == @movie.user %>
      <%= link_to("Edit", edit_movie_path(@movie), class: "btn btn-primary pull-right") %>
    <% end %>
  </div>
  <h2><%= @movie.title %></h2>
  <p><%= simple_format(@movie.description)%></p>
  <br>
  <table class="table">
    <thead>
      <tr>
        <th>评论内容</th>
        <th>评论者</th>
        <th>发表时间<th>
      </tr>
    </thead>
    <tbody>

      <%= render :partial => "review_item", :collection => @reviews, :as => :review %>
    </tbody>
  </table>

  <div class="text-center">
    <%= will_paginate @reviews %>
  </div>
</div>

app/views/reviews/edit.html.erb
<h2 class="text-center">编辑评论</h2>

<div clsss="row">
  <div class="col-md-4 col-md-offset-4">
    <%= simple_form_for [@movie,@review] do |f| %>
      <div class="form-group">
        <%= f.input :content, input_html: {class: "form-control" } %>
      </div>
      <div class="form-actions">
        <%= f.submit "Submit", disable_with: "Submiting...", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<h2 class="text-center">新增评论</h2>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= simple_form_for [@movie,@review] do |f| %>
      <div class="form-group">
        <%= f.input :content, input_html: { class: "form-control" } %>
      </div>
      <div class="form-actions">
        <%= f.submit "Submit", disable_with: "Submiting...", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="container-fluid text-center">
  <h1>Yay! Let's go to the movies!</h1>
  <h1>Yay! Let's go to the movies!</h1>
  <h1>Yay! Let's go to the movies!</h1>
  <h1>Yay! Let's go to the movies!</h1>
</div>